name: root

on:
  push:
    branches: [main, develop]
  pull_request:
    branches: [main, develop]

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      NEXTAUTH_SECRET: "secreat"
      DATABASE_URL: "file:./db.sqlite"
      NEXTAUTH_URL: "http://localhost:3000"
      DISCORD_CLIENT_ID: ""
      DISCORD_CLIENT_SECRET: ""

    strategy:
      matrix:
        node-version: [16.x]

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}
      - name: Install dependencies
        run: npm install --frozen-lockfile
      - run: npm run build
      - run: npm run lint
      - name: Test
        run: npm run test
        env:
          TURBO_TOKEN: ${{ secrets.TURBO_TOKEN }}
          TURBO_TEAM: malarivnat
          TURBO_REMOTE_ONLY: "true"
