import { type NextPage } from "next";
import Head from "next/head";
import { Button } from "ui/Button";

const Home: NextPage = () => {
  return (
    <>
      <Head>
        <title>Akij Food & Beverage Ltd</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="flex min-h-screen flex-col items-center justify-center bg-gradient-to-b from-[#2e026d] to-[#15162c]">
        <div className="container flex flex-col items-center justify-center gap-12 px-4 py-16 ">
          <h1 className="text-5xl font-extrabold tracking-tight text-white sm:text-[5rem]">
            Akij Food & Beverage Ltd.
          </h1>
          <Button />
        </div>
      </main>
    </>
  );
};

export default Home;
