name: root

on:
  push:
    branches: [main, develop]
  pull_request:
    branches: [main, develop]

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      NEXTAUTH_SECRET: "secreat"
      DATABASE_URL: "file:./db.sqlite"
      NEXTAUTH_URL: "http://localhost:3000"
      DISCORD_CLIENT_ID: ""
      DISCORD_CLIENT_SECRET: ""
      NEXT_PUBLIC_SANITY_DATASET: "production"
      NEXT_PUBLIC_SANITY_PROJECT_ID: "p3mskeo"

    strategy:
      matrix:
        node-version: [16.x]

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}
      - name: Install dependencies
        run: npm install --frozen-lockfile
      - run: npm run build
      - run: npm run lint
      - name: Test
        run: npm run test
        env:
          TURBO_TOKEN: ${{ secrets.TURBO_TOKEN }}
          TURBO_TEAM: malarivnat
          TURBO_REMOTE_ONLY: "true"

  install:
  ui-chrome-tests:
    runs-on: ubuntu-latest
    container: cypress/browsers:node12.18.3-chrome87-ff82
    needs: install
    strategy:
      fail-fast: false
      matrix:
        # run copies of the current job in parallel
        containers: [1, 2, 3, 4, 5]
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Download the build folders
        uses: actions/download-artifact@v3
        with:
          name: build
          path: build

      - name: "UI Tests - Chrome"
        uses: cypress-io/github-action@v5.x.x # use the explicit version number
        with:
          # we have already installed all dependencies above
          install: false
          start: yarn start:ci
          wait-on: "http://localhost:3000"
          wait-on-timeout: 120
          browser: chrome
          record: true
          parallel: true
          group: "UI - Chrome"
          spec: cypress/tests/ui/*

        env:
          NEXTAUTH_SECRET: "secreat"
          DATABASE_URL: "file:./db.sqlite"
          NEXTAUTH_URL: "http://localhost:3000"
          DISCORD_CLIENT_ID: ""
          DISCORD_CLIENT_SECRET: ""
          NEXT_PUBLIC_SANITY_DATASET: "production"
          NEXT_PUBLIC_SANITY_PROJECT_ID: "p3mskeo"
